/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#704700",
        "on-background": "#2c2f30",
        "secondary": "#0a6a1d",
        "primary-fixed": "#5aa2ff",
        "surface-dim": "#d1d5d7",
        "primary-fixed-dim": "#4795f3",
        "on-secondary-fixed-variant": "#0a6a1d",
        "surface-variant": "#dadddf",
        "surface-container": "#e6e8ea",
        "inverse-primary": "#4e9af9",
        "tertiary-container": "#f9a825",
        "tertiary": "#7f5200",
        "on-tertiary": "#fff0e2",
        "secondary-dim": "#005d16",
        "tertiary-fixed": "#f9a825",
        "on-error-container": "#570008",
        "on-tertiary-container": "#4e3000",
        "surface-container-highest": "#dadddf",
        "surface-bright": "#f5f6f7",
        "outline-variant": "#abadae",
        "primary-container": "#5aa2ff",
        "secondary-container": "#9df898",
        "on-secondary-container": "#006016",
        "secondary-fixed-dim": "#90e98b",
        "surface-container-high": "#e0e3e4",
        "error-dim": "#9f0519",
        "on-surface": "#2c2f30",
        "on-secondary-fixed": "#004b0f",
        "on-primary-container": "#002347",
        "on-primary": "#eef3ff",
        "on-surface-variant": "#595c5d",
        "outline": "#757778",
        "surface-container-low": "#eff1f2",
        "inverse-on-surface": "#9b9d9e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#301c00",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#5a3800",
        "primary": "#005caa",
        "surface": "#f5f6f7",
        "error-container": "#fb5151",
        "primary-dim": "#005095",
        "tertiary-fixed-dim": "#e99b13",
        "on-primary-fixed-variant": "#002c57",
        "inverse-surface": "#0c0f10",
        "on-error": "#ffefee",
        "background": "#f5f6f7",
        "on-secondary": "#d1ffc8",
        "error": "#b31b25",
        "surface-tint": "#005caa",
        "secondary-fixed": "#9df898",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "24px",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
